# Generated by Django 3.0.2 on 2020-01-20 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('select_city', '0004_auto_20200108_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='select_city.Countries'),
        ),
        migrations.AlterField(
            model_name='countries',
            name='continent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country', to='select_city.Continents'),
        ),
    ]
